### PR TITLE
Fix Bundler setup

### LINKED ISSUE #4: Error: cannot load such file -- google/apis/analyticsreporting_v4
After setting up my config file, I ran `brew formula-analytics`, and on the first run, it installed a bunch of gems, then gave me this error. On subsequent runs, it immediately gives the error.

<details>
<blockquote><pre><samp>
Error: cannot load such file -- google/apis/analyticsreporting_v4
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics/cmd/brew-formula-analytics.rb:33:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:96:in `<main>'
</samp></pre></blockquote>
</details>

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Some more tricks to setup the RubyGems require path properly that will hopefully survive Ruby version changes.
CC @jcount @alyssais @ilovezfs can you see if this works for you? Thanks!

Fixes #4.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@JCount @ilovezfs @alyssais Changed the approach from vendoring here, can you give it a go? Thanks.

**Comment by alyssais** [comment]
No change for me :(. I'll have a look into it and see if I can figure out what's going on.

**Comment by alyssais** [comment]
Bundler seems to be installing the gems into `vendor/ruby/ruby/2.4.0` for me.

**Comment by alyssais** [comment]
The problem appears to be that child gem processes are not run with the same version of Ruby as Homebrew itself — they use `env ruby`, so whichever `ruby` binary is first in the PATH. One fix for this would be making Homebrew prepend the directory of the HOMEBREW_RUBY_PATH to PATH — I just hacked this in and found it solved the problem, but only with the changes in this PR as well.

**Comment by JCount** [comment]
I had to completely blow away the contents of my `~/.gem` folder, but once I did this works fine for me. Mind you, that is with `HOMEBREW_RUBY_PATH=/usr/local/opt/ruby/bin/ruby` set. 👍

**Comment by MikeMcQuaid** [comment]
Seems like this is marginally better so merging.

> One fix for this would be making Homebrew prepend the directory of the HOMEBREW_RUBY_PATH to PATH — I just hacked this in and found it solved the problem, but only with the changes in this PR as well.

This seems like a good idea for a Homebrew/brew PR 👍

**Comment by MikeMcQuaid** [comment]
> One fix for this would be making Homebrew prepend the directory of the HOMEBREW_RUBY_PATH to PATH — I just hacked this in and found it solved the problem, but only with the changes in this PR as well.

I think it'd be better, thinking about this again, to scope this only to the child `bundle` process here rather than doing so globally as we're trying to have fewer rather than more things like that added to the PATH.

**Pull request merged**
