### PR TITLE
Use v3 SQL instead of v1 InfluxDB API

### PR DESCRIPTION
**Pull request by Bo98**
PyCall approach.

The whole migration should fix `count_being_weird_categories` stuff and also fix (presumably) inaccurate analytics data we are seeing: https://formulae.brew.sh/analytics/os-version/30d/.

Bulk of the code required an extra nest as data is now streamed in batches so I recommend viewing the diff with whitespace disabled.

Replaces and closes #440

### CODE REVIEW

**Comment by Bo98** [comment]
This may require adding `actions/setup-python` to formulae.brew.sh CI.

Could also `brew install python@version` at runtime but that will be slower.

**Comment by SMillerDev** [comment]
I'd say `setup-Python`

**Review by MikeMcQuaid — APPROVED** [review]
Looks good, thanks @Bo98!

**Comment by MikeMcQuaid** [comment]
Great work here, thanks @Bo98!

**Pull request merged**
