### PR TITLE
test

### PR DESCRIPTION
**Pull request by Bo98**
Testing CI failure

### CODE REVIEW

**Comment by Bo98** [comment]
> rpc error: code = ResourceExhausted desc = External error: External error: External error: Execution error for 'deduplicate batches'
caused by
Resources exhausted: Failed to allocate additional 1015888 bytes for ExternalSorterMerge[0] with 0 bytes already allocated - maximum available is 735681

**Comment by Bo98** [comment]
This seems like a regression on InfluxDB's side. We were able to query over 200 million rows before and now it chokes around at least half that.

**Comment by Bo98** [comment]
You can reproduce with very simple queries like `SELECT COUNT(*) FROM "formula_install"`

**Comment by MikeMcQuaid** [comment]
@Bo98 worth reaching out to their support I think.

**Pull request closed without merging**
